# Generated by Django 3.0.2 on 2020-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('tone', models.CharField(max_length=8)),
                ('synthetic', models.CharField(max_length=8)),
            ],
        ),
    ]
