# Generated by Django 3.0.2 on 2020-02-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_effect_group_inventory_location_log_track_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='type',
        ),
    ]
