# Generated by Django 3.0.2 on 2020-02-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
